name: Build Secure Framework
on:
  workflow_dispatch: # يتيح لك تشغيل البناء يدوياً

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Setup iOS SDK
        run: |
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          # [cite_start]نستخدم SDK 14.5 لضمان التوافق مع الحماية الجديدة [cite: 1-19]

      - name: Build Framework
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
        
      - name: Upload Framework Result
        uses: actions/upload-artifact@v3
        with:
          name: MetalCoreEngine-Framework
          [cite_start]path: packages/*.framework # سيتم رفع المجلد كفريم ورك جاهز [cite: 1-19]
